//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReceptorDL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceptorDeUsuario
    {
        public int ReceptorDeUsuarioId { get; set; }
        public int UsuarioId { get; set; }
        public string ReceptorRFC { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Receptor Receptor { get; set; }
    }
}
