//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReceptorDL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReceptorDataModelContainer : DbContext
    {
        public ReceptorDataModelContainer()
            : base("name=ReceptorDataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Comprobante> Comprobantes { get; set; }
        public DbSet<Emisor> Emisores { get; set; }
        public DbSet<Receptor> Receptores { get; set; }
        public DbSet<Usuario> Usuarios { get; set; }
        public DbSet<EmisorDeUsuario> EmisoresDeUsuario { get; set; }
        public DbSet<ReceptorDeUsuario> ReceptoresDeUsuario { get; set; }
        public DbSet<Rol> Roles { get; set; }
    }
}
