//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReceptorDL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Comprobantes = new HashSet<Comprobante>();
        }
    
        public int UsuarioId { get; set; }
        public string Nickname { get; set; }
        public string Nombre { get; set; }
        public string CorreoElectronico { get; set; }
    
        public virtual ICollection<Comprobante> Comprobantes { get; set; }
    }
}
